name: Bug Report
description: File a bug report
title: "[emtf-issue-tracker]: "
labels: ["bug"]
assignees:
  - earlman
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏🏻
  - type: dropdown
    id: contact-type
    attributes:
      label: Best way to contact you about this?
      options:
        - fb messenger
        - text me
        - call me
        - email me
        - nah I'm busy
  - type: textarea
    id: screenshot
    attributes:
      label: Show us what happened
      description: Drag & Drop or Paste an image
      placeholder: "![image](...)"
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Provide a description if you think it's necessary
      placeholder: Can be as long or as short as you like.
  - type: dropdown
    id: browsers
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
